USE ORG;
#QUESTION 1:
SELECT FIRST_NAME AS WORKER_NAME FROM WORKER ;
#QUESTION 2:
SELECT DISTINCT DEPARTMENT FROM WORKER;
#QUESTION 3:
SELECT LEFT(FIRST_NAME, 3) FROM WORKER;
#QUESTION 4:
SELECT distinct length(DEPARTMENT) FROM WORKER;
#QUESTION 5:
SELECT * FROM WORKER ORDER BY FIRST_NAME ASC , DEPARTMENT DESC;
#QUESTION 6:
SELECT * FROM WORKER WHERE DEPARTMENT = 'ADMIN';
#QUESTION 7:
SELECT * FROM WORKER WHERE SALARY BETWEEN 100000 AND 500000;
#QUESTION 8:
SELECT * FROM WORKER WHERE SALARY  >=50000 AND SALARY <=100000;
#QUESTION 9:
select * from worker where WORKER_ID IN (SELECT WORKER_ID FROM WORKER WHERE WORKER_ID %2=0);
#QUESTION 10:
SELECT * FROM Worker WHERE YEAR(joining_date) = 2014 AND MONTH(joining_date) = 2;

